version: '3.9'

services:
  db:
    image: mysql:8
    container_name: mysql_blog
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blogs_database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: blogbuddy_app
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data:
